In [ ]:
import pandas as pd
import numpy as np
from pycaret.classification import *

In [ ]:
df=pd.read_csv("preprocess_file1.csv")

In [ ]:
df.head(2)

,CVE ID Number,Publish Date,Software Type,Vendor,Product,CVSS Score,Confidentiality Impact,Integrity Impact,Availibility Impact,Access Complexity,Authentication,Vulnerability Type,Summary Text
0,CVE-2013-2512,2021-01-26,Application,Ftpd Project,Ftpd,10,Complete,Complete,Complete,Low,Not required,Execute Code,the ftpd gem 0.2.1 for ruby allows remote atta...
1,CVE-2020-3686,2021-01-21,Hardware,Qualcomm,Apq8009,10,Complete,Complete,Complete,Low,Not required,unknown,possible memory out of bound issue during musi...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13196 entries, 0 to 13195
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CVE ID Number           13196 non-null  object
 1   Publish Date            13196 non-null  object
 2   Software Type           13196 non-null  object
 3   Vendor                  13196 non-null  object
 4   Product                 13196 non-null  object
 5   CVSS Score              13196 non-null  int64
 6   Confidentiality Impact  13196 non-null  object
 7   Integrity Impact        13196 non-null  object
 8   Availibility Impact     13196 non-null  object
 9   Access Complexity       13196 non-null  object
 10  Authentication          13196 non-null  object
 11  Vulnerability Type      13196 non-null  object
 12  Summary Text            13196 non-null  object
dtypes: int64(1), object(12)
memory usage: 1.3+ MB

In [ ]:
df["Publish Date"]=pd.to_datetime(df["Publish Date"],format='%Y-%m-%d')

In [ ]:
# df.info()

In [ ]:
filtered_df = df[(df['Publish Date'] >= '2021-10-01')]

In [ ]:
filtered_df.shape

(939, 13)

In [ ]:
# # filtered_df.index=filtered_df["Publish Date"]
# import matplotlib.pyplot as plt

In [ ]:
# plt.figure(figsize=(16,8))
# plt.plot(filtered_df['CVSS Score'], label='current month cvvs score')

In [ ]:
# os_df=df[(df["Software Type"] == 'OS')]

In [ ]:
# os_df.head(2)
# os_df.shape

(2696, 13)

In [ ]:
# database=os_df['Access Complexity']=="High"
# # print(database)
# df_tr=os_df[database]
# # print(df_tr)
# os_df=os_df.append([df_tr]*42,ignore_index=True)

In [ ]:
# os_df["Access Complexity"].value_counts()

In [ ]:
# X=os_df[["Vendor","Product","Confidentiality Impact","Integrity Impact","Vulnerability Type","Authentication","Access Complexity"]]
X_= df[["Software Type","Product","Integrity Impact","Authentication","Access Complexity","Vulnerability Type","CVSS Score"]]
# X.shape
# X.tail()
X_.head()

,Software Type,Product,Integrity Impact,Authentication,Access Complexity,Vulnerability Type,CVSS Score
0,Application,Ftpd,Complete,Not required,Low,Execute Code,10
1,Hardware,Apq8009,Complete,Not required,Low,unknown,10
2,Hardware,Apq8009,Complete,Not required,Low,unknown,10
3,Application,MQ,Complete,Not required,Low,Execute Code,10
4,OS,Element Os,Complete,Not required,Low,Execute Code,10

In [ ]:
# clf = setup(data = X, target = 'Access Complexity',feature_selection = True,high_cardinality_features = ['Product',"Vendor","Vulnerability Type"],fix_imbalance = True, session_id=123,imputation_type='iterative')
clf_ = setup(data = X_, target = 'CVSS Score', session_id=123,high_cardinality_features = ['Product',"Vulnerability Type"],fix_imbalance = True,feature_selection = True,imputation_type='iterative')

In [ ]:
best = compare_models()

In [ ]:
CVV_score = create_model('gbc')

In [ ]:
tuned_Cvv = tune_model(CVV_score)

In [ ]:
final_Cvv = finalize_model(tuned_Cvv)

In [ ]:
save_model(final_Cvv,'Final_Cvv')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[],
                                       target='CVSS Score', time_features=[])),
                 ('imputer',
                  Iterative_Imputer(add_indicator=False,
                                    classifier=LGBMClassifier(boosting_type='gbdt',
                                                              class_weight=None,
                                                              colsample_byt...
                                             learning_rate=0.15, loss='deviance',
                                             max_depth=7, max_features=1.0,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.02,
                                             min_impurity_split=None,
                                             min_samples_leaf=5,
                                             min_samples_split=5,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=230,
                                             n_iter_no_change=None,
                                             presort='deprecated',
                                             random_state=123, subsample=0.85,
                                             tol=0.0001, validation_fraction=0.1,
                                             verbose=0, warm_start=False)]],
          verbose=False),
 'Final_Cvv.pkl')

In [ ]:
# saved_final_Cvv = load_model('Final_Cvv')

In [ ]:
# new_prediction=predict_model(saved_final_Cvv, data=unseen_)

In [ ]:
# new_prediction/