## Library load

In [20]:
import pandas as  pd
df=pd.read_csv("preprocess_file.csv")

### Data load

In [29]:
df.head(2)

,CVE ID Number,Publish Date,Software Type,Vendor,Product,CVSS Score,Confidentiality Impact,Integrity Impact,Availibility Impact,Access Complexity,Vulnerability Type,Summary Text,Authentication
0,CVE-2013-2512,2021-01-26,Application,Ftpd Project,Ftpd,10,0,0,0,Low,Execute Code,the ftpd gem 0.2.1 for ruby allows remote atta...,0
1,CVE-2020-3686,2021-01-21,Hardware,Qualcomm,Apq8009,10,0,0,0,Low,unknown,possible memory out of bound issue during musi...,0

In [30]:
X=df[["Software Type","Vendor","Product","Access Complexity"]]

In [33]:
# database=X['Access Complexity']=="High"
# # # print(database)
# df_tr=X[database]
# # print(df_tr)
# X=X.append([df_tr]*22,ignore_index=True)

In [34]:
# X["Access Complexity"].value_counts()

High      7521
Low       7514
Medium    5573
Name: Access Complexity, dtype: int64

### loading pycaret library

In [35]:
from pycaret.classification import *
# high_cardinality_features = ['Product',"Vendor","Vulnerability Type"],
# high_cardinality_features = ['Product',"Vendor"]
# fix_imbalance = True

### setup

In [36]:
exp_mclf101 = setup(data = X, target = 'Access Complexity', session_id=123,imputation_type='iterative')

### comparing algorithm

In [37]:
best = compare_models()

### creating model using Logistic Regression

In [40]:
Acc = create_model('rf')

### fine tuning model

In [41]:
# tuned_Acc = tune_model(Acc)

In [10]:
# plot_model(tuned_Acc, plot = 'confusion_matrix')

In [11]:
# plot_model(tuned_Acc, plot = 'class_report')

In [12]:
# evaluate_model(tuned_Acc)

In [13]:
# predict_model(tuned_Acc)

### final model

In [42]:
final_Acc = finalize_model(Acc)

### saving model

In [43]:
save_model(final_Acc,'Final_Acc')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[],
                                       target='Access Complexity',
                                       time_features=[])),
                 ('imputer',
                  Iterative_Imputer(add_indicator=False,
                                    classifier=LGBMClassifier(boosting_type='gbdt',
                                                              class_weight=None,
                                                              colsam...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='auto',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_impurity_split=None,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=100, n_jobs=-1,
                                         oob_score=False, random_state=123,
                                         verbose=0, warm_start=False)]],
          verbose=False),
 'Final_Acc.pkl')

### loading model

In [44]:
saved_final_Acc = load_model('Final_Acc')

Transformation Pipeline and Model Successfully Loaded

#### unseen data

In [45]:
X={"Software Type":"OS","Vendor":"microsoft","Product":"window 10"}
X=pd.DataFrame([X])

#### doing prediction on unseen data

In [47]:
new_prediction=predict_model(saved_final_Acc, data=X)

In [48]:
new_prediction.head()

  Software Type     Vendor    Product Label  Score
0            OS  microsoft  window 10   Low  0.825